import { NextResponse } from 'next/server';
import crypto from 'node:crypto';
import { cookies } from 'next/headers';
import { db } from '@/lib/db';
import { agentReply } from '@/lib/agent';
import { hashPassword, requireAdmin, safeEqualHex, SESSION_COOKIE } from '@/lib/auth';
import { scoreLead } from '@/lib/scoring';

type Ctx={params:Promise<{path:string[]}>};
const unauthorized=()=>NextResponse.json({error:'Unauthorized'},{status:401});
const key=async(c:Ctx)=>(await c.params).path.join('/');

export async function GET(req:Request,c:Ctx){
  const k=await key(c);const sql=db();
  if(k==='crm/bootstrap'){const r=await sql`select count(*)::int as count from admin_users`;return NextResponse.json({needs_setup:Number(r[0]?.count||0)===0})}
  if(k==='crm/me'){const user=await requireAdmin();return user?NextResponse.json({user}):unauthorized()}
  if(!await requireAdmin())return unauthorized();
  if(k==='crm/metrics'){const [counts,stages,recent]=await Promise.all([sql`select count(*) filter(where created_at>=now()-interval '30 days')::int as new_leads,count(*) filter(where stage='Qualified')::int as qualified,count(*) filter(where stage='Demo Booked')::int as booked,coalesce(sum(estimated_value) filter(where stage not in ('Won','Lost')),0)::float as pipeline_value from leads`,sql`select stage,count(*)::int as count from leads group by stage`,sql`select id,name,company,email,stage,score,created_at from leads order by created_at desc limit 8`]);return NextResponse.json({metrics:counts[0],stages,recent})}
  if(k==='crm/leads'){const u=new URL(req.url),stage=u.searchParams.get('stage')||'',q=(u.searchParams.get('q')||'').trim();let rows;if(stage&&q)rows=await sql`select * from leads where stage=${stage} and (name ilike ${'%'+q+'%'} or coalesce(company,'') ilike ${'%'+q+'%'} or coalesce(email,'') ilike ${'%'+q+'%'}) order by updated_at desc limit 250`;else if(stage)rows=await sql`select * from leads where stage=${stage} order by updated_at desc limit 250`;else if(q)rows=await sql`select * from leads where name ilike ${'%'+q+'%'} or coalesce(company,'') ilike ${'%'+q+'%'} or coalesce(email,'') ilike ${'%'+q+'%'} order by updated_at desc limit 250`;else rows=await sql`select * from leads order by updated_at desc limit 250`;return NextResponse.json({leads:rows})}
  if(/^crm\/leads\/[^/]+$/.test(k)){const id=k.split('/')[2];const [lead,notes,tasks,activities,conversations]=await Promise.all([sql`select * from leads where id=${id} limit 1`,sql`select * from notes where lead_id=${id} order by created_at desc`,sql`select * from tasks where lead_id=${id} order by created_at desc`,sql`select * from activities where lead_id=${id} order by created_at desc limit 100`,sql`select c.*,coalesce(json_agg(json_build_object('role',m.role,'content',m.content,'created_at',m.created_at) order by m.created_at) filter(where m.id is not null),'[]') as messages from conversations c left join messages m on m.conversation_id=c.id where c.lead_id=${id} group by c.id order by c.created_at desc`]);if(!lead[0])return NextResponse.json({error:'Not found'},{status:404});return NextResponse.json({lead:lead[0],notes,tasks,activities,conversations})}
  if(k==='crm/tasks'){const rows=await sql`select t.*,l.name as lead_name,l.company as lead_company from tasks t left join leads l on l.id=t.lead_id order by (t.status='open') desc,t.due_at nulls last,t.created_at desc limit 250`;return NextResponse.json({tasks:rows})}
  if(k==='crm/settings'){const rows=await sql`select key,value from settings order by key`;return NextResponse.json({settings:Object.fromEntries(rows.map((r:any)=>[r.key,r.value]))})}
  if(k==='crm/export'){const rows=await sql`select name,company,email,phone,industry,stage,score,estimated_value,source,automation_need,biggest_problem,owner,created_at,updated_at from leads order by updated_at desc`;const headers=['name','company','email','phone','industry','stage','score','estimated_value','source','automation_need','biggest_problem','owner','created_at','updated_at'];const cell=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=[headers.join(','),...rows.map((r:any)=>headers.map(h=>cell(r[h])).join(','))].join('\n');return new Response(csv,{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="pulsebridge-leads.csv"'}})}
  return NextResponse.json({error:'Not found'},{status:404});
}

export async function POST(req:Request,c:Ctx){
  const k=await key(c);const sql=db();
  if(k==='crm/bootstrap'){const existing=await sql`select count(*)::int as count from admin_users`;if(Number(existing[0]?.count||0)>0)return NextResponse.json({error:'Setup is already complete.'},{status:409});const b=await req.json(),name=String(b.name||'PulseBridge Admin').trim(),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(!email.includes('@')||password.length<10)return NextResponse.json({error:'Use a valid email and a password of at least 10 characters.'},{status:400});const salt=crypto.randomBytes(24).toString('hex'),passwordHash=hashPassword(password,salt);let users;try{users=await sql`insert into admin_users(email,name,password_salt,password_hash) values(${email},${name},${salt},${passwordHash}) returning id,email,name`}catch{return NextResponse.json({error:'Setup is already complete.'},{status:409})}const token=crypto.randomBytes(36).toString('base64url'),tokenHash=crypto.createHash('sha256').update(token).digest('hex');await sql`insert into admin_sessions(user_id,token_hash,expires_at) values(${users[0].id},${tokenHash},now()+interval '14 days')`;const res=NextResponse.json({ok:true,user:users[0]});res.cookies.set(SESSION_COOKIE,token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:60*60*24*14});return res}
  if(k==='crm/login'){const b=await req.json(),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');const rows=await sql`select id,email,name,password_salt,password_hash from admin_users where lower(email)=${email} limit 1`,user=rows[0];if(!user)return NextResponse.json({error:'Invalid email or password.'},{status:401});const candidate=hashPassword(password,String(user.password_salt));if(!safeEqualHex(candidate,String(user.password_hash)))return NextResponse.json({error:'Invalid email or password.'},{status:401});const token=crypto.randomBytes(36).toString('base64url'),tokenHash=crypto.createHash('sha256').update(token).digest('hex');await sql`delete from admin_sessions where expires_at<=now()`;await sql`insert into admin_sessions(user_id,token_hash,expires_at) values(${user.id},${tokenHash},now()+interval '14 days')`;const res=NextResponse.json({ok:true,user:{id:user.id,email:user.email,name:user.name}});res.cookies.set(SESSION_COOKIE,token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:60*60*24*14});return res}
  if(k==='crm/logout'){const store=await cookies(),token=store.get(SESSION_COOKIE)?.value;if(token){const h=crypto.createHash('sha256').update(token).digest('hex');await sql`delete from admin_sessions where token_hash=${h}`}const res=NextResponse.json({ok:true});res.cookies.set(SESSION_COOKIE,'',{httpOnly:true,path:'/',maxAge:0});return res}
  if(k==='leads'){try{const b=await req.json(),name=String(b.name||'').trim(),email=String(b.email||'').trim().toLowerCase(),consent=b.consent===true||b.consent==='true';if(!name||!email.includes('@')||!consent)return NextResponse.json({error:'Name, valid email and contact consent are required.'},{status:400});const monthly=Number(b.monthly_lead_volume||0)||0,p={monthly_lead_volume:monthly,timeline:String(b.timeline||''),budget_range:String(b.budget_range||''),industry:String(b.industry||''),biggest_problem:String(b.biggest_problem||'')},score=scoreLead(p),stage=score>=65?'Qualified':'New';const found=await sql`select id from leads where lower(email)=${email} limit 1`;let lead;if(found[0])lead=(await sql`update leads set name=${name},company=${String(b.company||'')},phone=${String(b.phone||'')},industry=${p.industry},monthly_lead_volume=${monthly},biggest_problem=${p.biggest_problem},preferred_contact=${String(b.preferred_contact||'')},timeline=${p.timeline},budget_range=${p.budget_range},consent=${consent},score=${score},stage=case when stage in ('Won','Lost') then stage else ${stage} end,updated_at=now() where id=${found[0].id} returning *`)[0];else lead=(await sql`insert into leads(name,company,email,phone,industry,monthly_lead_volume,biggest_problem,preferred_contact,timeline,budget_range,consent,score,stage,source) values(${name},${String(b.company||'')},${email},${String(b.phone||'')},${p.industry},${monthly},${p.biggest_problem},${String(b.preferred_contact||'')},${p.timeline},${p.budget_range},${consent},${score},${stage},'website') returning *`)[0];await sql`insert into activities(lead_id,type,description,metadata) values(${lead.id},'lead_capture','Website audit request captured',${JSON.stringify({source:'website',score})}::jsonb)`;if(score>=65){const open=await sql`select id from tasks where lead_id=${lead.id} and status='open' and title='Follow up with qualified lead' limit 1`;if(!open[0])await sql`insert into tasks(lead_id,title,description,due_at,priority) values(${lead.id},'Follow up with qualified lead','Review qualification details and contact the prospect.',now()+interval '1 day','high')`}return NextResponse.json({ok:true,id:lead.id,score,stage})}catch(e){console.error(e);return NextResponse.json({error:'Could not save the lead.'},{status:500})}}
  if(k==='chat'){try{const b=await req.json(),session=String(b.session_id||'').trim(),messages=Array.isArray(b.messages)?b.messages.slice(-30):[];if(!session||!messages.length)return NextResponse.json({error:'Invalid conversation.'},{status:400});const reply=await agentReply(messages);let conv=(await sql`select id,lead_id from conversations where session_id=${session} limit 1`)[0];if(!conv)conv=(await sql`insert into conversations(session_id) values(${session}) returning id,lead_id`)[0];const last=messages[messages.length-1];if(last?.role==='user')await sql`insert into messages(conversation_id,role,content) values(${conv.id},'user',${String(last.content).slice(0,6000)})`;await sql`insert into messages(conversation_id,role,content) values(${conv.id},'assistant',${reply.slice(0,6000)})`;await sql`update conversations set updated_at=now() where id=${conv.id}`;const userText=messages.filter((m:any)=>m.role==='user').map((m:any)=>String(m.content)).join(' '),email=(userText.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0],phone=(userText.match(/(?:\+?1[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}/)||[])[0],consent=/\b(yes|i agree|consent|contact me|you can contact|please contact)\b/i.test(userText);if(email&&consent&&!conv.lead_id){const score=scoreLead({biggest_problem:userText,monthly_lead_volume:messages.length>=4?50:0,timeline:userText,budget_range:userText,industry:userText});let lead=(await sql`select * from leads where lower(email)=${email.toLowerCase()} limit 1`)[0];if(!lead)lead=(await sql`insert into leads(name,email,phone,biggest_problem,consent,score,stage,source,qualification_summary) values('AI Advisor Lead',${email.toLowerCase()},${phone||''},${userText.slice(0,3000)},true,${score},${score>=65?'Qualified':'New'},'ai_advisor',${'AI Advisor conversation: '+userText.slice(0,1800)}) returning *`)[0];await sql`update conversations set lead_id=${lead.id},summary='AI Advisor qualification captured' where id=${conv.id}`;await sql`insert into activities(lead_id,type,description,metadata) values(${lead.id},'ai_qualification','AI Advisor captured a qualified conversation',${JSON.stringify({session,score})}::jsonb)`;if(score>=65)await sql`insert into tasks(lead_id,title,description,due_at,priority) values(${lead.id},'Follow up with AI-qualified lead','Review the AI Advisor transcript and contact the prospect.',now()+interval '1 day','high')`}return NextResponse.json({reply})}catch(e){console.error(e);return NextResponse.json({reply:'I can still help qualify your workflow. What is the biggest missed-call or follow-up problem in the business today?'})}}
  if(!await requireAdmin())return unauthorized();
  if(k==='crm/leads'){const b=await req.json(),name=String(b.name||'').trim();if(!name)return NextResponse.json({error:'Name is required.'},{status:400});const score=scoreLead(b);const rows=await sql`insert into leads(name,company,email,phone,industry,monthly_lead_volume,biggest_problem,preferred_contact,source,stage,score,estimated_value,automation_need,timeline,budget_range,current_crm,consent,owner,tags,next_follow_up_at) values(${name},${String(b.company||'')},${String(b.email||'').toLowerCase()},${String(b.phone||'')},${String(b.industry||'')},${Number(b.monthly_lead_volume||0)},${String(b.biggest_problem||'')},${String(b.preferred_contact||'')},'manual',${String(b.stage||'New')},${Number(b.score??score)},${Number(b.estimated_value||0)},${String(b.automation_need||'')},${String(b.timeline||'')},${String(b.budget_range||'')},${String(b.current_crm||'')},${Boolean(b.consent)},${String(b.owner||'')},${Array.isArray(b.tags)?b.tags:[]},${b.next_follow_up_at||null}) returning *`;await sql`insert into activities(lead_id,type,description) values(${rows[0].id},'lead_created','Lead created manually in CRM')`;return NextResponse.json({lead:rows[0]})}
  if(/^crm\/leads\/[^/]+\/notes$/.test(k)){const id=k.split('/')[2],b=await req.json(),body=String(b.body||'').trim();if(!body)return NextResponse.json({error:'Note is required.'},{status:400});const rows=await sql`insert into notes(lead_id,body) values(${id},${body}) returning *`;await sql`insert into activities(lead_id,type,description) values(${id},'note_added','CRM note added')`;return NextResponse.json({note:rows[0]})}
  if(k==='crm/tasks'){const b=await req.json(),title=String(b.title||'').trim();if(!title)return NextResponse.json({error:'Task title is required.'},{status:400});const rows=await sql`insert into tasks(lead_id,title,description,due_at,priority) values(${b.lead_id||null},${title},${String(b.description||'')},${b.due_at||null},${String(b.priority||'normal')}) returning *`;return NextResponse.json({task:rows[0]})}
  return NextResponse.json({error:'Not found'},{status:404});
}

export async function PATCH(req:Request,c:Ctx){const k=await key(c);if(!await requireAdmin())return unauthorized();const sql=db();
  if(/^crm\/leads\/[^/]+$/.test(k)){const id=k.split('/')[2],b=await req.json();const rows=await sql`update leads set name=coalesce(${b.name??null},name),company=coalesce(${b.company??null},company),email=coalesce(${b.email??null},email),phone=coalesce(${b.phone??null},phone),industry=coalesce(${b.industry??null},industry),stage=coalesce(${b.stage??null},stage),score=coalesce(${b.score??null},score),estimated_value=coalesce(${b.estimated_value??null},estimated_value),automation_need=coalesce(${b.automation_need??null},automation_need),biggest_problem=coalesce(${b.biggest_problem??null},biggest_problem),current_crm=coalesce(${b.current_crm??null},current_crm),timeline=coalesce(${b.timeline??null},timeline),budget_range=coalesce(${b.budget_range??null},budget_range),owner=coalesce(${b.owner??null},owner),next_follow_up_at=coalesce(${b.next_follow_up_at??null},next_follow_up_at),last_contact_at=case when ${Boolean(b.mark_contacted)} then now() else last_contact_at end,updated_at=now() where id=${id} returning *`;if(!rows[0])return NextResponse.json({error:'Not found'},{status:404});await sql`insert into activities(lead_id,type,description,metadata) values(${id},'lead_updated','Lead record updated',${JSON.stringify({stage:b.stage||undefined})}::jsonb)`;return NextResponse.json({lead:rows[0]})}
  if(/^crm\/tasks\/[^/]+$/.test(k)){const id=k.split('/')[2],b=await req.json();const rows=await sql`update tasks set status=coalesce(${b.status??null},status),priority=coalesce(${b.priority??null},priority),due_at=coalesce(${b.due_at??null},due_at),completed_at=case when ${b.status==='done'} then now() when ${b.status==='open'} then null else completed_at end where id=${id} returning *`;return NextResponse.json({task:rows[0]})}
  return NextResponse.json({error:'Not found'},{status:404})}

export async function PUT(req:Request,c:Ctx){const k=await key(c);if(!await requireAdmin())return unauthorized();if(k!=='crm/settings')return NextResponse.json({error:'Not found'},{status:404});const b=await req.json(),sql=db();for(const [setting,value] of Object.entries(b))await sql`insert into settings(key,value,updated_at) values(${setting},${JSON.stringify(value)}::jsonb,now()) on conflict(key) do update set value=excluded.value,updated_at=now()`;return NextResponse.json({ok:true})}
