import Link from 'next/link';
import { SiteShell, LeadForm, ROICalculator } from '@/components/Public';

const services=[
['01','Missed-Call AI','Answer, qualify and route inbound calls so demand is not lost when your team is busy.'],
['02','Lead Follow-Up','Instant, consistent follow-up workflows that move new inquiries toward booked appointments.'],
['03','CRM Automation','Capture, score, route and track every lead in one operating system instead of scattered inboxes.'],
['04','Booking Automation','Connect qualification to appointment scheduling and reduce the back-and-forth.'],
['05','Review Systems','Trigger professional review requests after completed jobs and keep reputation workflows organized.'],
['06','Custom Workflows','Build the handoffs, alerts and automations that fit the way your business actually operates.']
];
export default function Home(){return <SiteShell>
<section className="hero"><div className="container"><div className="eyebrow">AI OPERATIONS FOR SERVICE BUSINESSES</div><h1 className="display">Turn every lead into an <span className="soft">operational advantage.</span></h1><p className="subhead">PulseBridge installs AI reception, lead follow-up, booking and CRM automation so service businesses respond faster, miss fewer opportunities and run with tighter execution.</p><div className="hero-actions"><Link className="btn btn-primary" href="/contact">Get an AI Automation Audit →</Link><Link className="btn btn-ghost" href="#services">Explore the system</Link></div><div className="trust-row"><span><i/>No fake ROI claims</span><span><i/>CRM-connected lead capture</span><span><i/>AI agent with safe fallback</span><span><i/>Built for real operations</span></div></div></section>
<section className="metric-band"><div className="container metrics"><div className="metric"><strong>24/7</strong><span>Lead intake availability</span></div><div className="metric"><strong>1 CRM</strong><span>Shared system of record</span></div><div className="metric"><strong>7 stages</strong><span>Clear pipeline visibility</span></div><div className="metric"><strong>0 dead forms</strong><span>Every inquiry enters workflow</span></div></div></section>
<section className="section" id="services"><div className="container"><div className="eyebrow">THE AUTOMATION STACK</div><h2 className="section-title">Serious infrastructure for businesses that cannot afford sloppy follow-up.</h2><p className="section-copy">We focus on the parts of the customer journey where speed, consistency and visibility directly affect revenue operations.</p><div className="grid grid-3" style={{marginTop:42}}>{services.map(s=><div className="card service-card" key={s[0]}><div><div className="service-number">{s[0]}</div><div className="icon-box">✦</div></div><div><h3>{s[1]}</h3><p>{s[2]}</p></div></div>)}</div></div></section>
<section className="section" id="how"><div className="container grid grid-2"><div><div className="eyebrow">HOW IT WORKS</div><h2 className="section-title">Audit. Architect. Install. Optimize.</h2><p className="section-copy">No bloated transformation program. We identify the highest-value workflow first, connect it to your operating data, then expand from proof.</p></div><div className="card steps"><div className="step"><h3>Find the leak</h3><p>Map missed calls, delayed responses, manual handoffs and CRM gaps.</p></div><div className="step"><h3>Design the automation</h3><p>Choose the smallest system that can create a meaningful operating improvement.</p></div><div className="step"><h3>Connect the workflow</h3><p>Route lead data, conversations and tasks into a shared CRM pipeline.</p></div><div className="step"><h3>Measure and improve</h3><p>Use real activity and pipeline data to decide what automation comes next.</p></div></div></div></section>
<section className="section-tight"><div className="container"><div className="card" style={{padding:'44px'}}><div className="grid grid-2"><div><span className="pill"><span className="dot-live"/>AI Advisor installed</span><h2 className="section-title" style={{fontSize:'clamp(2.2rem,4vw,3.6rem)'}}>Your website should qualify leads before your team touches the inbox.</h2></div><div><p className="section-copy">The PulseBridge AI Advisor asks the right operating questions, records the conversation, and moves qualified prospects into the CRM with context intact.</p><Link className="btn btn-primary" href="/contact" style={{marginTop:24}}>See your automation fit →</Link></div></div></div></div></section>
<section className="section-tight"><div className="container"><div className="eyebrow">ROI SCENARIO</div><h2 className="section-title">Put numbers around the leak before you automate it.</h2><p className="section-copy" style={{marginBottom:30}}>Use your own lead volume and job value to model the upside of recovering a fraction of currently lost opportunities.</p><ROICalculator/></div></section>
<section className="section"><div className="container"><div className="eyebrow">FAQ</div><h2 className="section-title">Questions serious operators ask first.</h2><div className="grid grid-2" style={{marginTop:28}}><div className="card"><h3>Does this replace my staff?</h3><p className="section-copy">The system is designed to remove repetitive response and routing work while keeping humans in control of important customer decisions.</p></div><div className="card"><h3>Do I need a new CRM?</h3><p className="section-copy">Not necessarily. PulseBridge can operate as the CRM layer or be adapted around an existing system when integration makes sense.</p></div><div className="card"><h3>What happens if the AI provider is unavailable?</h3><p className="section-copy">The public advisor includes a deterministic qualification fallback, so lead intake does not become a dead end.</p></div><div className="card"><h3>Can this connect to phone, SMS and calendars?</h3><p className="section-copy">Yes. The CRM is structured for those integrations; exact providers are selected during implementation based on your workflow and budget.</p></div></div></div></section>
<section className="section"><div className="container"><div style={{textAlign:'center',marginBottom:36}}><div className="eyebrow">START WITH THE AUDIT</div><h2 className="section-title">Build the system around your real bottleneck.</h2><p className="section-copy" style={{margin:'auto'}}>Tell us what is breaking in the current process. The request goes directly into the PulseBridge CRM.</p></div><LeadForm/></div></section>
</SiteShell>}
