import { notFound } from 'next/navigation';
import { SiteShell, LeadForm } from '@/components/Public';
import Link from 'next/link';

const pages:Record<string,React.ReactNode>={
  services:<><section className="hero"><div className="container"><div className="eyebrow">SERVICES</div><h1 className="display">Automation built around <span className="soft">business outcomes.</span></h1><p className="subhead">Not random AI tools. Connected systems that improve how leads are handled, routed and converted.</p></div></section><section className="section-tight"><div className="container grid grid-2">{[['AI Receptionist','Inbound call handling, qualification, routing and missed-call recovery.'],['Lead Response Engine','Immediate follow-up sequences for web, call and campaign leads.'],['CRM Operating System','Pipeline, contact history, notes, tasks, scoring and activity visibility.'],['Appointment Automation','Qualification-to-booking workflows with handoff controls.'],['Reputation Workflow','Review requests and follow-up after completed work.'],['Custom Business Automation','Integrations and internal workflows built around your specific process.']].map(([a,b],i)=><div className="card" key={a}><div className="service-number">0{i+1}</div><h2>{a}</h2><p className="section-copy">{b}</p></div>)}</div></section><section className="section-tight"><div className="container"><div className="card" style={{textAlign:'center'}}><h2 className="section-title">Start with the highest-value bottleneck.</h2><Link className="btn btn-primary" href="/contact">Request an audit →</Link></div></div></section></>,
  industries:<><section className="hero"><div className="container"><div className="eyebrow">INDUSTRIES</div><h1 className="display">Built for businesses where <span className="soft">response time matters.</span></h1><p className="subhead">PulseBridge is strongest where incoming calls, quote requests and appointments are valuable enough that missed follow-up becomes expensive.</p></div></section><section className="section-tight"><div className="container grid grid-3">{['HVAC & Mechanical','Plumbing','Electrical','Roofing','Landscaping','Automotive Service','Med Spas','Dental & Clinics','Legal Services','Home Services','Property Services','Other appointment-driven businesses'].map((x,i)=><div className="card" key={x}><div className="service-number">{String(i+1).padStart(2,'0')}</div><h3>{x}</h3><p className="section-copy">AI intake, follow-up, booking and CRM workflow adapted to the operating pattern of your team.</p></div>)}</div></section></>,
  pricing:<><section className="hero"><div className="container"><div className="eyebrow">PACKAGES</div><h1 className="display">Buy the outcome, <span className="soft">not the tool count.</span></h1><p className="subhead">Final pricing depends on call volume, integrations and workflow complexity. Packages are scoped around the operating result.</p></div></section><section className="section-tight"><div className="container grid grid-3">{[['Foundation','Lead Response',['Lead capture','CRM pipeline','Automated follow-up','Basic qualification']],['Recommended','AI Growth System',['AI advisor / receptionist','Lead scoring and routing','CRM automation','Booking workflow','Follow-up tasks']],['Advanced','Automation OS',['Multiple agents/workflows','Custom integrations','Advanced CRM processes','Operational reporting']]].map(([label,name,features]:any)=><div className={`card price-card ${label==='Recommended'?'featured':''}`} key={name}><div className="price-label">{label}</div><h3>{name}</h3><div className="price">Custom</div><div className="price-note">Scope based on actual workflow complexity and volume.</div><ul className="feature-list">{features.map((f:string)=><li key={f}>{f}</li>)}</ul><Link className={`btn ${label==='Recommended'?'btn-primary':'btn-ghost'}`} href="/contact">Scope this package</Link></div>)}</div></section></>,
  contact:<><section className="hero"><div className="container"><div className="eyebrow">AI AUTOMATION AUDIT</div><h1 className="display">Show us the bottleneck. <span className="soft">We’ll map the system.</span></h1><p className="subhead">Your request goes directly into the CRM so the conversation starts with context.</p></div></section><section className="section-tight"><div className="container"><LeadForm/></div></section></>,
  privacy:<Legal title="Privacy Policy"><p>PulseBridge collects information you choose to submit through forms and the AI Advisor, such as contact details, company information, automation needs and conversation content.</p><p>We use this information to respond to your request, qualify business needs, maintain CRM records and improve service delivery. Do not submit passwords, payment card data, regulated health information or other highly sensitive information through public chat.</p><p>You may request correction or deletion of submitted business contact information by contacting PulseBridge.</p><p className="small">This starter policy should be reviewed for the jurisdictions and integrations actually used by the business.</p></Legal>,
  terms:<Legal title="Terms of Use"><p>This website provides information about PulseBridge AI automation services and lets prospective customers request an audit or interact with an automated advisor.</p><p>AI-generated responses are informational and may be incomplete. Final scope, pricing, requirements and performance expectations are defined only in an accepted service agreement.</p><p>You agree not to misuse the website or attempt unauthorized access to the CRM.</p><p>PulseBridge does not guarantee specific revenue, savings or conversion outcomes from the general information shown here.</p><p className="small">These starter terms should be reviewed by qualified counsel before broad commercial use.</p></Legal>
};
function Legal({title,children}:{title:string;children:React.ReactNode}){return <section className="section"><div className="container" style={{maxWidth:820}}><div className="eyebrow">LEGAL</div><h1 className="section-title">{title}</h1><div className="card">{children}</div></div></section>}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const content=pages[slug];if(!content)notFound();return <SiteShell>{content}</SiteShell>}
